apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.media.name }}
{{- if .Values.volumes.media.annotations }}
  annotations:
{{ toYaml .Values.volumes.media.annotations | indent 4 }}
{{- end }}
spec:
  storageClassName: {{ .Values.volumes.media.storageClass | default .Values.volumes.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.media.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.homemedia.name }}
{{- if .Values.volumes.homemedia.annotations }}
  annotations:
{{ toYaml .Values.volumes.homemedia.annotations | indent 4 }}
{{- end }}
spec:
  storageClassName: {{ .Values.volumes.homemedia.storageClass | default .Values.volumes.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.homemedia.size }}
